name: cryptobot_tg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - matplotlib
  - ca-certificates
  - pip:
      - aiogram==3.20.0.post0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - attrs==25.3.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - python-dotenv==1.1.0
      - frozenlist==1.6.0
      - h11==0.14.0
      - idna==3.10
      - magic-filter==1.0.12
      - mplfinance==0.12.10b0
      - multidict==6.4.3
      - outcome==1.3.0.post0
      - pandas-ta==0.3.14b0
      - propcache==0.3.1
      - pybit==5.10.0
      - pycryptodome==3.22.0
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pysocks==1.7.1
      - requests==2.32.3
      - selenium==4.30.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - technical==1.5.0
      - talib
      - trio==0.29.0
      - trio-websocket==0.12.2
      - typing-extensions==4.13.0
      - typing-inspection==0.4.0
      - urllib3==2.3.0
      - websocket-client==1.8.0
      - wsproto==1.2.0
      - yarl==1.20.0