name: cryptobot_tg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - matplotlib
  - ca-certificates
  - ta-lib
  - python-dotenv
  - requests
  - websocket-client
  - pip:
      - aiogram==3.20.0
      - aiohttp==3.11.18
      - annotated-types==0.7.0
      - attrs==25.3.0
      - certifi==2025.1.31
      - mplfinance==0.12.10b0
      - multidict==6.4.3
      - pandas-ta==0.3.14b0
      - pybit==5.10.0
      - pycryptodome==3.22.0
      - pydantic==2.11.3
      - typing-extensions==4.13.0
      - urllib3==2.3.0
      - yarl==1.20.0