name: cryptobot_tg
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - numpy
  - pandas
  - pip
  - ta-lib
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - numexpr
  - bottleneck
  - tzdata
  - setuptools
  - wheel
  - six
  - python-dateutil
  - pytz
  - tk
  - readline
  - openssl
  - ca-certificates

  - pip:
      - attrs==25.3.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - h11==0.14.0
      - idna==3.10
      - outcome==1.3.0.post0
      - pybit==5.10.0
      - pycryptodome==3.22.0
      - pysocks==1.7.1
      - requests==2.32.3
      - selenium==4.30.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - technical==1.5.0
      - trio==0.29.0
      - trio-websocket==0.12.2
      - typing-extensions==4.13.0
      - urllib3==2.3.0
      - websocket-client==1.8.0
      - wsproto==1.2.0
